const quotes = [
  "I'm done chasing likes - I choose real connection now.",
  "That's not me anymore.",
  "I already know what happens if I go there. I don't need to test it again.",
  "This is an old solution to a problem I've already solved.",
  "I'm not avoiding life - I'm building one I actually want.",
  'That was me before I started choosing intentionally.',
  "That guy was always escaping - I'm done with escape.",
  "That's what I did when I didn't believe in myself. I do now.",
  "I know what this urge leads to, and it's not where I'm going.",
  'My values lead me - not my feelings.',
  "I've already won this battle - I just need to remember that.",
  "I don't negotiate with old habits.",
  'I trust myself more than I trust this urge.',
  "Freedom isn't found in escape - it's found in showing up.",
  "I've got better things to build.",
  'I walk toward purpose, not away from discomfort.',
  "I'm not running from pain - I'm becoming the man who can face it.",
  'This urge is a signal, not a command.',
  "There's nothing for me down that path.",
  "I've already proven I can choose differently.",
  'This is just a ghost of who I used to be.',
  'Every time I choose presence, I strengthen my future.',
  'Old Matt would click. New Matt chooses.',
  'This moment is a chance to prove who I am.',
  "This isn't about resisting - it's about remembering who I am.",
  "I am not a slave to comfort. I'm building something real.",
  "The man I'm becoming makes decisions with intention.",
  "Urges don't control me - clarity does.",
  "I've already quit this. This is just the echo.",
  "I don't do distractions. I do direction.",
  "There's no reward in relapse.",
  "This isn't temptation - it's a test, and I pass tests now.",
];

const randomIndex = Math.floor(Math.random() * quotes.length);
document.getElementById('quote').textContent = quotes[randomIndex];
